### PR TITLE
Automaton-based global compiler (Do not merge yet)

### PR DESCRIPTION
**Pull request by smolkaj**
There is some work needed before we can merge this in.

### CODE REVIEW

**Comment by arjunguha** [comment]
We should delete the old global compiler.

**Comment by arjunguha** [comment]
Can we delete this?

**Comment by smolkaj** [comment]
@arjunguha: Looks like the global compiler has been merged into the unified branch https://github.com/frenetic-lang/frenetic/commit/b771476df7c1a15891db6e2187010451ce5cf255, but not into master. Will unified eventually become the new master branch?

**Comment by craig-riecke** [comment]
@smolkaj Unified is the new master - I merged the contents of this pull request by hand since master had diverged so far.  The global compiler is not actually called by anything yet, but the "virtual" branch addresses that AFAIK.  So I think we can delete this branch.  We probably should also delete "unified" too...

**Comment by craig-riecke** [comment]
Ooops, closed by accident.

**Pull request closed without merging**
