### PR TITLE
Fixed eval for VSwitch and VPort headers

### PR DESCRIPTION
**Pull request by poddarh**

### CODE REVIEW

**Comment by arjunguha** [comment]
@smolkaj @jnfoster and others: I assume nobody objects to this change? All it does is make the NetKAT interpreter accept packets with virtual switches/ports.

**Comment by smolkaj** [comment]
Looks good!

**Comment by smolkaj** [comment]
damn, I accidentally reinvoked travis

**Comment by jnfoster** [comment]
+1

SGTM

**Pull request merged**
