### PR TITLE
Fixes to make things compile with latest JaneStreet libraries

### PR DESCRIPTION
**Pull request by smolkaj**
@jnfoster I think this should be ready now (your cstruct patch has been merged in @ v3.0.2).

Cool extra: we can now use [@deriving hash] 👍 

This addreses #562.

### CODE REVIEW

**Comment by smolkaj** [comment]
We're not currently running any tests:
```
...
Finished, 309 targets (2 cached) in 00:01:42.
ocaml setup.ml -test 
You are doing something unexpected with the tests. No tests have 
been run. You should use the inline_tests_runner script to run 
tests.
```

**Comment by basus** [comment]
Ready to roll. Someone merge please?

**Comment by smolkaj** [comment]
Sweet!!

**Comment by jnfoster** [comment]
Congrats!

**Pull request merged**
