### PR TITLE
Webkat

### PR DESCRIPTION
**Pull request by arjunguha**
**Not ready to merge**

Here are some things that are left to do before we can add this to master:

- [ ] Remove Java bindings (somehow move them to a separate branch)
- [x] Let the current `update` URL take pure NetKAT in the body
- [x] Create `update_json` URL with pure JSON encoding. (master has a JSON encoding that we can use.)
- [ ] Demo applications? We have two forwarding applications (learning.py and repeater.py). It doesn't make sense to run them simultaneously. Let's add a silly monitoring application to truly demo this system.
- [x] Remove WebKAT dependency on Ryu (https://github.com/frenetic-lang/frenetic/blob/redisnib/lang/py/netkat/webkat.py#L102). This has been creating trouble for @nbraga, who just wants to hack a custom topo discovery packet. Let's just decode the bytes and let other clients use ryu if they want.

### CODE REVIEW

**Comment by arjunguha** [comment]
See the checklist above. All those features are now in master. This pull request should not be merged. But, we should extract the Java bindings and polish them as needed. E.g., they could be ported to use NetKAT-JSON.

**Comment by smolkaj** [comment]
Can this be closed? @arjunguha

**Comment by arjunguha** [comment]
@smolkaj yes, I'm pretty sure the code from this branch has been pulled in in other ways.

**Comment by smolkaj** [comment]
Ok, I'll throw it out then.

**Comment by smolkaj** [comment]
I guess we can keep the branch, doesn't hurt.

**Comment by arjunguha** [comment]
It hurts.

**Comment by smolkaj** [comment]
Feel free to delete it :)

**Pull request closed without merging**
