### PR TITLE
Fixed Bad File Descriptor on Dump Subcommand

### PR DESCRIPTION
**Pull request by craig-riecke**
Addresses #499 @smolkaj If you could check this when you have a moment ... it works but I don't know if it might be wrecking performance.

### CODE REVIEW

**Comment by smolkaj** [comment]
Looks good.
Any idea why the old code didn't work? Some kind of nasty garbage collection problem? You shouldn't really have problems like that in a language like OCaml...

**Comment by craig-riecke** [comment]
`Int_channel.with_file` opens the file, applies the function to the open channel, then closes the channel.  The original code basically handed off a closed channel to `policy_of_stream` which freaked it out - that's why it passed the type checks, but failed at runtime.

**Comment by smolkaj** [comment]
Ops...
I'm used to just looking at the type of a function to determine it's behavior. This is the first time I get screwed by OCaml's impurity.

**Comment by smolkaj** [comment]
(Should we move to Haskell?)

**Comment by smolkaj** [comment]
just kidding

**Comment by basus** [comment]
We should actually build our own home-grown pragmatic functional programming language that fixes all of OCaml's existing warts, and then reimplement Frenetic in that.

**Comment by craig-riecke** [comment]
Amen!  Every program worth writing is worth inventing a new programming language for!

**Comment by smolkaj** [comment]
Actually, I think linear types would have helped with this.

**Pull request merged**
