### PR TITLE
Refactored frenetic executable

### PR DESCRIPTION
**Pull request by smolkaj**
The main change is that now, each command has it's own specification, parameters, and flags. (Previously, all commands shared the same flags and parameters).
This makes it trivial to add new commands - in fact I integrated a dump command (which used to be a separate executable).
All functionality from before should be preserved.

As a nice side effect, `frenetic dump` can now be run on Macs because it doesn't use Async.

### CODE REVIEW

**Comment by smolkaj** [comment]
@craig-riecke: Could you take a look and check if the commands you typically use still work?

**Comment by craig-riecke** [comment]
@smolkaj: Yep - everything works great.  Much cleaner design too.  I fixed all the run.sh files in examples/virtual/*, even though "dump virtual" is not implemented yet.  (I didn't stop to check that before I changed the files).  They would've had to have been sooner or later anyway.  

If you want me to merge the pull request, lemme know, or you can handle it...

**Comment by smolkaj** [comment]
Great, thanks. Merging...

**Comment by smolkaj** [comment]
I forget to say, I'm in the process of getting the virtual compiler working again, so the examples will work soon.

**Pull request merged**
