### PR TITLE
Shell

### PR DESCRIPTION
**Pull request by jcollard**

### CODE REVIEW

**Comment by arjunguha** [comment]
Add mparser as a dependency to fix the build error.

**Comment by arjunguha** [comment]
(add mparser to the opam file)

**Comment by arjunguha** [comment]
@jnfoster and @jcollard we should talk about how to deal with mparser. It is a little annoying to use, because it relies on the pcre package, which requires a non-standard Linux package to be installed, AFAIK. 

Using monadic parsers is totally reasonable and we shouldn't not use them. But, see this:

https://bitbucket.org/cakeplus/mparser/issue/5/cut-a-release#comment-15494866

**Comment by jnfoster** [comment]
I'm all for using parser combinators, but it'd really really nice to not
acquire a dependency on pcre.

-N

**Comment by avsm** [comment]
The `re` library in OPAM is pure OCaml and has a thin `Re_pcre` shim layer.

**Comment by jnfoster** [comment]
Yo dawg, I heard you liked regular expressions, so I put pcre in your KAT.

On Tue, Feb 10, 2015 at 5:13 PM, Anil Madhavapeddy <notifications@github.com

**Comment by avsm** [comment]
Yo dawg, I heard you like dawgs, so I made you a dawg; https://github.com/samoht/dog

**Comment by arjunguha** [comment]
@avsm The trouble is mparser, which depends on pcre.

**Comment by arjunguha** [comment]
All this has been merged, right? Can we delete this branch and pull request? @jcollard

**Comment by jcollard** [comment]
yes.

**Pull request closed without merging**
