### PR TITLE
Unified standalone

### PR DESCRIPTION
**Pull request by reitblatt**
Separated OpenFlow into standalone binary (frenetic/openflow). Communicates with Frenetic through a tcp socket (localhost:8984). API is wrapped up and hidden behind async/Frenetic_OpenFlow0x01_Controller.ml. TCP port is configurable via command line args (-s), but the address is not (easy to add).

Logs its pid in /var/run/frenetic/openflow0x01.pid
Logs messages in /var/log/frenetic/openflow.log

@jnfoster @craig-riecke

### CODE REVIEW

**Comment by jnfoster** [comment]
@reitblatt I think we agreed to wait to merge this until TCP sockets are swapped in?

**Comment by reitblatt** [comment]
@jnfoster TCP sockets are now swapped in!

**Comment by craig-riecke** [comment]
After merging in master, I did some preliminary large tests that ran fine.  I need to do the following things:

* Write openflow log to user-configurable location, or at least the same location as frenetic.log
* Cleanup sockets etc. if OpenFlow server dies unexpectedly

**Comment by craig-riecke** [comment]
@jnfoster @arjunguha Do you have a preference between CmdLiner and Command for command line processing in OCaml?  I ask because the new Standalone Openflow process openflow.ml uses Command, while frenetic.ml uses Cmdliner.  I'd like to square them up.

**Comment by jnfoster** [comment]
I don't have a strong preference, but caeteris paribus, Jane Street Core
all the way.

**Comment by craig-riecke** [comment]
My plan is to add stuff related to Issue 429 here too, since it's gonna be a command line parameter supporting it (and it's only about 10 extra lines of code).  It'll be: 

```
--default-action {drop, controller, nop}
```

which will affect flow table rules generated at an FDD false branch.  The default will be drop, which is the current approach, so it won't affect any existing implementations.  "Nop" essentially generates no rule, or "let the switch decide."  It's for the Dell switches and their weird interpretation of L2/L3 rules.  "controller" mirrors OpenFlow 1.0 default behavior but generates the rule explicitly.

**Comment by jnfoster** [comment]
I'd like to discuss this further before proceeding. The current hack
doesn't seem sound to me...

-N

**Comment by craig-riecke** [comment]
Absolutely.  And I'd be happy to merge Mark's split-process changes into master if it's needed sooner-rather-than-later.

**Comment by arjunguha** [comment]
I could join.I didn't fully grok the edit.

**Comment by craig-riecke** [comment]
I'm ready to merge this into master.  The new executable is working nicely in Gates production.  So the overall changes are:

- Split process design.  frenetic now spawns the openflow executable (or openflow.native, depending on what it finds).  
- Configurable compiler.  You can either configure it through shell commands (in shell) or REST+JSON (in http-controller or compile-server).  Configuration parameters are:
-- cache_prepare: "keep" or "empty".  Defaults to "empty",
-- field_order: "default", "heuristic" or a < separated field list, e.g. "Switch < Vlan < EthSrc".  This matches functionality in shell.  Defaults to "heuristic"
-- remove_tail_drops: boolean.  Setting to true removes any drop rules generated on the False branches of FDD.  It only removes them from the end of the flow table, which is presumably all the rules generated by not's.  In particular, this removes the "Match All -> Drop" rule.  Defaults to false.  
-- dedup_flows: boolean.  True removes duplicate flows.  Defaults to false.
-- optimize: boolean: eliminates some redundancy in rules.  Defaults to true.

A few details may need polishing:

- The openflow executable writes to a separate log, ./openflow.log.  On the Gates servers, that means it's out of the standard log directory, and therefore doesn't get rotated.  I'd like both frenetic and openflow to wrote to a common syserr, but that doesn't look easily doable.  
- Using remove_tail_drops=true generates packet in's on OpenFlow 1.0 servers because the default action for a table miss is to go to the controller.  (If remove_tail_drops=false, as is the default, there are no table misses).  It's impossible to tell which pipe the table miss packet is bound for, since by definition there is no matching rule.  So frenetic just send it to a pipe called "table_miss" for all all apps.  It'd probably be better to have apps register a pipe name they want to see Table Miss packets on, but that's per-app configuration that we have no current mechanism for.  That sounds like it'd be overengineering for what is just a workaorund for Dell switches.      
- It'd be nice to guarantee a /config is executed before the next /update, but async makes this non-trivial.

**Comment by smolkaj** [comment]
@craig-riecke: Is there a strong reason why `dedup_flows` defaults to `false`? To comply with the NetKAT set semantics, this should be `true`.

**Comment by craig-riecke** [comment]
@smolkaj Nope, no strong reason.  I just used the default that was already there.  Fixed now.

**Comment by smolkaj** [comment]
@craig-riecke: Great.
I think I set the default to `false` when I initially implemented this so the compiler would behave as before.
However, now seems like a good time to make the correct behavior the default behavior.

**Pull request merged**
