### PR TITLE
Virtual

### PR DESCRIPTION
**Pull request by craig-riecke**
Virtual is now ready to be merged in.  A few small changes:

- Command line options were converted from cmdliner to Core Command, as per the new setup.  The only change is the policy file for the "global" compiler command is now "--policy-file" to match the corresponding command line option for the HTTP server, shell, etc.

- JSON parsing for Location (including Pipe and Query options) was reinstated

- JSON parsing for Switch and Vlan was changed to a string, so you would need to specify "switch": "12345" instead of "switch": 12345.  But the values were converted to an OCaml int/int64 afterwards, so it didn't make sense to do it this way.  (This would require changing the Python language bindings).

### CODE REVIEW

**Comment by craig-riecke** [comment]
Oh, and change the virtual subcommand arguments to be tagged with flag names like --vpolicy, etc.  Those are more unix-y and self-document the command better, but if you want to go back to anonymous, positional arguments lemme know.

**Comment by basus** [comment]
Looks like there's a problem with travis, but modulo that, is there a reason why this can't be merged now? Should someone be assigned to take a look at it?

**Comment by craig-riecke** [comment]
Lemme look at it real quick.  Travis is kind of flaky, so the fact that the last run was not successful is not usually a big deal.

**Comment by craig-riecke** [comment]
The actual travis build did complete successfully, so I'll merge it in.

**Pull request merged**
